### ISSUE TITLE
python-all required ?

### ISSUE THREAD

**Issue by Sispheor** [astraw/stdeb#153]
Hi,
I'm trying to build a package on Ubuntu 20.04. I only have python3 on my system.
I have this error:
```
dpkg-query: no packages found matching python-all
ERROR running: /usr/bin/dpkg-query --show --showformat=${Version} python-all
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    ('/usr/share/applications', ['indicator-ip.desktop'])  # desktop entry
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/stdeb/command/bdist_deb.py", line 27, in run
    self.run_command('sdist_dsc')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/stdeb/command/sdist_dsc.py", line 141, in run
    sign_dsc=self.sign_results,
  File "/usr/local/lib/python3.7/site-packages/stdeb/util.py", line 1416, in build_dsc
    python_defaults_version_str = get_version_str('python-all')
  File "/usr/local/lib/python3.7/site-packages/stdeb/util.py", line 276, in get_version_str
    stdout = get_cmd_stdout(args)
  File "/usr/local/lib/python3.7/site-packages/stdeb/util.py", line 251, in get_cmd_stdout
    raise RuntimeError('returncode %d', returncode)
RuntimeError: ('returncode %d', 1)
```

It seems that an `sudo apt install python-all` would does the job but lso bring back python2 which I would try to avoid.

Is this lib really mandatory now that python2 is deprecated?
Thanks for you support.

**Comment by dirk-thomas** [comment]
Resolved by #154.
