### ISSUE TITLE
Running under Fedora

### ISSUE THREAD

**Issue by SolidTux** [astraw/stdeb#159]
I tried to run this under Fedora, but it doesn't seem to work. There are packages for the dpkg tools, but the script seems to use `dpkg-query` to see if `debhelper` is installed. I've installed both of them, but as `debhelper` is installed through dnf it's not found.

Is there a way to bypass this check? Or use a different method depending on the distribution?

```
...
dpkg-query: Kein Paket gefunden, das auf debhelper passt
ERROR running: /usr/bin/dpkg-query --show --showformat=${Version} debhelper
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(
  File "/home/daniel/.local/share/virtualenvs/x-9cSVj0er/lib/python3.8/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/daniel/.local/share/virtualenvs/x-9cSVj0er/lib/python3.8/site-packages/stdeb/command/bdist_deb.py", line 33, in run
    self.run_command('sdist_dsc')
  File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/daniel/.local/share/virtualenvs/x-9cSVj0er/lib/python3.8/site-packages/stdeb/command/sdist_dsc.py", line 135, in run
    build_dsc(debinfo,
  File "/home/daniel/.local/share/virtualenvs/x-9cSVj0er/lib/python3.8/site-packages/stdeb/util.py", line 1418, in build_dsc
    debhelper_version_str = get_version_str('debhelper')
  File "/home/daniel/.local/share/virtualenvs/x-9cSVj0er/lib/python3.8/site-packages/stdeb/util.py", line 272, in get_version_str
    stdout = get_cmd_stdout(args)
  File "/home/daniel/.local/share/virtualenvs/x-9cSVj0er/lib/python3.8/site-packages/stdeb/util.py", line 261, in get_cmd_stdout
    raise RuntimeError('returncode %d', returncode)
RuntimeError: ('returncode %d', 1)
```

**Comment by dirk-thomas** [comment]
> Is there a way to bypass this check? Or use a different method depending on the distribution?

Probably not at the moment. I also don't know what could / should be used on Fedora instead. Please consider contributing to make this work for your use case.
