### ISSUE TITLE
Can not build packages with C extensions

### ISSUE THREAD

**Issue by fredde-fisk** [astraw/stdeb#90]
The C extension is only built for the default python version, which causes dh_python2 to output the following error message:

> E: dh_python2:145: extension for python2.6 is missing. Build extensions for all supported Python versions (`pyversions -vr`) or adjust X-Python-Version field or pass --no-guessing-versions to dh_python2

To reproduce, try for example to build a debian package from python-signalfd on a system with both python 2.6 and 2.7:

```
# pip install --download ./ python-signalfd
Downloading/unpacking python-signalfd
  Downloading python-signalfd-0.1.tar.gz
Saved ./python-signalfd-0.1.tar.gz
Running setup.py egg_info for package python-signalfd

Successfully downloaded python-signalfd
Cleaning up...

# ls -la
total 16
drwxr-xr-x 2 root root 4096 Dec 30 23:33 .
drwx------ 4 root root 4096 Dec 30 23:31 ..
-rw-r--r-- 1 root root 5305 Dec 30 23:33 python-signalfd-0.1.tar.gz

# py2dsc-deb python-signalfd-0.1.tar.gz 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
running the following command in directory: deb_dist/tmp_py2dsc/python-signalfd-0.1
/usr/bin/python setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/root/t/deb_dist --use-premade-distfile=/root/t/python-signalfd-0.1.tar.gz bdist_deb
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
running sdist_dsc
CALLING dpkg-source -b python-signalfd-0.1 python-signalfd_0.1.orig.tar.gz (in dir /root/t/deb_dist)
dpkg-source: info: using options from python-signalfd-0.1/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building python-signalfd using existing ./python-signalfd_0.1.orig.tar.gz
dpkg-source: info: building python-signalfd in python-signalfd_0.1-1.debian.tar.gz
dpkg-source: info: building python-signalfd in python-signalfd_0.1-1.dsc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package python-signalfd
dpkg-buildpackage: source version 0.1-1
dpkg-buildpackage: source changed by Jean-Paul Calderone <exarkun@twistedmatrix.com>
 dpkg-source --before-build python-signalfd-0.1
dpkg-source: info: using options from python-signalfd-0.1/debian/source/options: --extend-diff-ignore=\.egg-info$
 fakeroot debian/rules clean
dh clean --with python2 --buildsystem=python_distutils
   dh_testdir -O--buildsystem=python_distutils
   debian/rules override_dh_auto_clean
make[1]: Entering directory `/root/t/deb_dist/python-signalfd-0.1'
python setup.py clean -a
running clean
'build/lib.linux-x86_64-2.7' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
find . -name \*.pyc -exec rm {} \;
make[1]: Leaving directory `/root/t/deb_dist/python-signalfd-0.1'
   dh_clean -O--buildsystem=python_distutils
 dpkg-source -b python-signalfd-0.1
dpkg-source: info: using options from python-signalfd-0.1/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building python-signalfd using existing ./python-signalfd_0.1.orig.tar.gz
dpkg-source: info: building python-signalfd in python-signalfd_0.1-1.debian.tar.gz
dpkg-source: info: building python-signalfd in python-signalfd_0.1-1.dsc
 dpkg-genchanges -S -sa >../python-signalfd_0.1-1_source.changes
dpkg-genchanges: including full source code in upload
 dpkg-source --after-build python-signalfd-0.1
dpkg-source: info: using options from python-signalfd-0.1/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-buildpackage: full upload (original source is included)
dpkg-source: warning: extracting unsigned source package (python-signalfd_0.1-1.dsc)
dpkg-source: info: extracting python-signalfd in python-signalfd-0.1
dpkg-source: info: unpacking python-signalfd_0.1.orig.tar.gz
dpkg-source: info: unpacking python-signalfd_0.1-1.debian.tar.gz
running bdist_deb
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package python-signalfd
dpkg-buildpackage: source version 0.1-1
dpkg-buildpackage: source changed by Jean-Paul Calderone <exarkun@twistedmatrix.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build python-signalfd-0.1
dpkg-source: info: using options from python-signalfd-0.1/debian/source/options: --extend-diff-ignore=\.egg-info$
 fakeroot debian/rules clean
dh clean --with python2 --buildsystem=python_distutils
   dh_testdir -O--buildsystem=python_distutils
   debian/rules override_dh_auto_clean
make[1]: Entering directory `/root/t/deb_dist/python-signalfd-0.1'
python setup.py clean -a
running clean
'build/lib.linux-x86_64-2.7' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
find . -name \*.pyc -exec rm {} \;
make[1]: Leaving directory `/root/t/deb_dist/python-signalfd-0.1'
   dh_clean -O--buildsystem=python_distutils
 debian/rules build
dh build --with python2 --buildsystem=python_distutils
   dh_testdir -O--buildsystem=python_distutils
   dh_auto_configure -O--buildsystem=python_distutils
   debian/rules override_dh_auto_build
make[1]: Entering directory `/root/t/deb_dist/python-signalfd-0.1'
python setup.py build --force
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/signalfd
copying signalfd/__init__.py -> build/lib.linux-x86_64-2.7/signalfd
creating build/lib.linux-x86_64-2.7/signalfd/test
copying signalfd/test/test_signalfd.py -> build/lib.linux-x86_64-2.7/signalfd/test
copying signalfd/test/__init__.py -> build/lib.linux-x86_64-2.7/signalfd/test
running build_ext
building 'signalfd._signalfd' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/signalfd
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c signalfd/_signalfd.c -o build/temp.linux-x86_64-2.7/signalfd/_signalfd.o
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/signalfd/_signalfd.o -o build/lib.linux-x86_64-2.7/signalfd/_signalfd.so
make[1]: Leaving directory `/root/t/deb_dist/python-signalfd-0.1'
   dh_auto_test -O--buildsystem=python_distutils
 fakeroot debian/rules binary
dh binary --with python2 --buildsystem=python_distutils
   dh_testroot -O--buildsystem=python_distutils
   dh_prep -O--buildsystem=python_distutils
   dh_installdirs -O--buildsystem=python_distutils
   debian/rules override_dh_auto_install
make[1]: Entering directory `/root/t/deb_dist/python-signalfd-0.1'
python setup.py install --force --root=debian/python-python-signalfd --no-compile -O0 --install-layout=deb  
running install
running build
running build_py
running build_ext
running install_lib
creating debian/python-python-signalfd/usr
creating debian/python-python-signalfd/usr/lib
creating debian/python-python-signalfd/usr/lib/python2.7
creating debian/python-python-signalfd/usr/lib/python2.7/dist-packages
creating debian/python-python-signalfd/usr/lib/python2.7/dist-packages/signalfd
copying build/lib.linux-x86_64-2.7/signalfd/__init__.py -> debian/python-python-signalfd/usr/lib/python2.7/dist-packages/signalfd
copying build/lib.linux-x86_64-2.7/signalfd/_signalfd.so -> debian/python-python-signalfd/usr/lib/python2.7/dist-packages/signalfd
creating debian/python-python-signalfd/usr/lib/python2.7/dist-packages/signalfd/test
copying build/lib.linux-x86_64-2.7/signalfd/test/test_signalfd.py -> debian/python-python-signalfd/usr/lib/python2.7/dist-packages/signalfd/test
copying build/lib.linux-x86_64-2.7/signalfd/test/__init__.py -> debian/python-python-signalfd/usr/lib/python2.7/dist-packages/signalfd/test
running install_egg_info
Writing debian/python-python-signalfd/usr/lib/python2.7/dist-packages/python_signalfd-0.1.egg-info
make[1]: Leaving directory `/root/t/deb_dist/python-signalfd-0.1'
   dh_install -O--buildsystem=python_distutils
   dh_installdocs -O--buildsystem=python_distutils
   dh_installchangelogs -O--buildsystem=python_distutils
   dh_installexamples -O--buildsystem=python_distutils
   dh_installman -O--buildsystem=python_distutils
   dh_installcatalogs -O--buildsystem=python_distutils
   dh_installcron -O--buildsystem=python_distutils
   dh_installdebconf -O--buildsystem=python_distutils
   dh_installemacsen -O--buildsystem=python_distutils
   dh_installifupdown -O--buildsystem=python_distutils
   dh_installinfo -O--buildsystem=python_distutils
   dh_python2 -O--buildsystem=python_distutils
E: dh_python2:145: extension for python2.6 is missing. Build extensions for all supported Python versions (`pyversions -vr`) or adjust X-Python-Version field or pass --no-guessing-versions to dh_python2
make: *** [binary] Error 3
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    "Topic :: Software Development :: Libraries :: Python Modules",
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/stdeb/command/bdist_deb.py", line 48, in run
    util.process_command(syscmd,cwd=target_dirs[0])
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 169, in process_command
    check_call(args, cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 45, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
ERROR running: /usr/bin/python setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/root/t/deb_dist --use-premade-distfile=/root/t/python-signalfd-0.1.tar.gz bdist_deb
ERROR in deb_dist/tmp_py2dsc/python-signalfd-0.1
```

**Comment by p1otr** [comment]
could you try stdeb from Debian's python-stdeb package?
I think I fixed it in my use_pybuild_buildsystem.patch
